trigger:
- main

pool:
  name: Default
  demands: godot  

steps:
- script: ls
- script: $(godot-exe-location)/godot --export "Web"
  displayName: 'Godot export to Web'

- task: AzureStaticWebApp@0
  condition: or(and(eq('${{ variables['Build.SourceBranchName'] }}', 'main'), ne('${{ variables['Build.Reason'] }}', 'PullRequest')), eq('${{ variables['Build.Reason'] }}', 'Manual'))
  inputs:
    working_directory: '/Da Fish/dist/web'
    app_location: '/'
    skip_app_build: true
    skip_api_build: true
    is_static_export: true
    azure_static_web_apps_api_token: $(static-web-app-deployment-token)
    production_branch: 'main'