trigger:
- main

pool:
  name: Default
  demands: godot  

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: $(godot-exe-location)/godot
  displayName: 'test godot exe'

- task: AzureStaticWebApp@0
  condition: or(and(eq('${{ variables['Build.SourceBranchName'] }}', 'main'), ne('${{ variables['Build.Reason'] }}', 'PullRequest')), eq('${{ variables['Build.Reason'] }}', 'Manual'))
  inputs:
    app_location: '/dist/web'
    skip_app_build: true
    skip_api_build: true
    is_static_export: true
    azure_static_web_apps_api_token: $(static-web-app-deployment-token)
    production_branch: 'main'